#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE-$0}")" || exit
devtools/bin/vpc /vance +shaders /mksln shaders

make -Bnwk -no-silent -j"$(nproc)" -fshaders.mak | compiledb
#bear -- make -Bnwk -no-silent -j"$(nproc)" -fshaders.mak

