#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE-$0}")" || exit
devtools/bin/vpc /vance +maptools /mksln maptools

make -Bnwk -no-silent -j"$(nproc)" -fmaptools.mak | compiledb
#bear -- make -Bnwk -no-silent -j"$(nproc)" -fmaptools.mak

