#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE-$0}")" || exit
devtools/bin/vpc /vance +everything /mksln everything

make -Bnwk -no-silent -j"$(nproc)" -feverything.mak | compiledb
#bear -- make -Bnwk -no-silent -j"$(nproc)" -feverything.mak

