#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE-$0}")" || exit
devtools/bin/vpc /vance +game +shaders /mksln games

make -Bnwk -no-silent -j"$(nproc)" -fgames.mak | compiledb
#bear -- make -Bnwk -no-silent -j"$(nproc)" -fgames.mak
